import CharacterCard from 'dh-marvel/components/characters/CharacterCard'
import { Character } from 'interfaces/comic'
import { GetStaticPaths, GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Container from '@mui/material/Container'
import { getCharacter, getCharacters } from 'dh-marvel/services/marvel/marvel.service'

interface Props {
    character: Character
}

const CharacterPage: NextPage<Props> = ({ character }) => {

    const { query } = useRouter()

    return (
        <>
            <Head>
                <title>DH Marvel</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container maxWidth="lg" sx={{ marginTop: '20px', marginBottom: '50px' }}>
                <CharacterCard character={character} />
            </Container>

        </>
    )
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
    const id = parseInt(params?.id as string);
    const character = await getCharacter(id);

    return {
        props: {
            character
        },
        revalidate: 60 * 60
    }
}
export const getStaticPaths: GetStaticPaths = async () => {

    const data = await getCharacters();
    const paths = data?.data.results.map((character: Character) => ({ params: { id: character.id.toString() } }))

    return {
        paths,
        fallback: 'blocking',
    };
}

export default CharacterPage