import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { getComics } from 'dh-marvel/services/marvel/marvel.service';
import { Comics, Comic } from 'interfaces/comic';
import { Container, Pagination, Box } from '@mui/material';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import ComicsGrid from 'dh-marvel/components/comics/home/ComicsGrid';
import PaginationBar from 'dh-marvel/components/pagination/PaginationBar';

interface Props {
    comics: Comics
}

const itemsPerPage = 12;

const Index: NextPage<Props> = ({ comics }) => {

    return (
        <>
            <Head>
                <title>DH Marvel</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BodySingle title={"Comics Marvel"}>
                <Container maxWidth="lg" sx={{ marginTop: '20px', marginBottom: '50px' }}>
                    <PaginationBar comics={comics} itemsPerPage={itemsPerPage} />
                    <ComicsGrid comics={comics} />
                    <PaginationBar comics={comics} itemsPerPage={itemsPerPage} />
                </Container>
            </BodySingle>
        </>
    )
}


export const getServerSideProps: GetServerSideProps = async ({ query, res }) => {

    const { page } = query
    // console.log({page});

    const offset = itemsPerPage * Number(page) - itemsPerPage
    const comics = await getComics(offset, itemsPerPage)
    // console.log({ comics });

    res.setHeader(
        'Cache-Control',
        'public, s-maxage=10, stale-while-revalidate=59'
    )
    return {
        props: {
            comics
        }
    }
}


export default Index
