import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import ComicCard from 'dh-marvel/components/card';
import { getComics } from 'dh-marvel/services/marvel/marvel.service';
import { Comics } from 'interfaces/comic';
import { Grid, Container } from '@mui/material';

interface Props {
    comics: Comics,
}


const Index: NextPage<Props> = ({ comics }) => {
    console.log({ comics })
    const comicsArray = comics.data.results

    return (
        <>
            <Head>
                <title>DH Marvel</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BodySingle title={"Comics Marvel"}>
                <Container maxWidth="lg">
                    <Grid container spacing={2}>
                        {comicsArray.map((comic) => (
                            <Grid item xs={12} sm={6} md={4}>
                                <ComicCard comic={comic} />
                            </Grid>
                        ))}
                    </Grid>
                </Container>
            </BodySingle>
        </>
    )
}

export const getStaticProps: GetStaticProps = async () => {
    const comics = await getComics()
    console.log({ comics })
    return {
        props: {
            comics
        }
    }
}



export default Index
